export const EVENTS = [
  {
    id: 1,
    title: 'IAU Tech Summit 2026',
    date: 'Jun 12, 2026',
    location: 'Engineering Faculty, B Block – Auditorium',
    category: 'Conference',
    seats: 200,
    booked: 148,
    img: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80&fit=crop',
    status: 'Open',
    description: 'Annual technology conference featuring keynote speakers from leading tech companies. Topics include AI, cybersecurity, and modern software development practices.',
    organizer: 'Faculty of Engineering',
  },
  {
    id: 2,
    title: 'Spring Cultural Festival',
    date: 'Jun 20, 2026',
    location: 'Campus Main Square',
    category: 'Cultural',
    seats: 500,
    booked: 500,
    img: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80&fit=crop',
    status: 'Full',
    description: 'Celebrate the diversity of IAU with traditional performances, cultural foods, and exhibitions from student clubs representing 30+ countries.',
    organizer: 'Student Affairs Office',
  },
  {
    id: 3,
    title: 'Entrepreneurship Workshop',
    date: 'Jul 3, 2026',
    location: 'Business Faculty, Conference Hall',
    category: 'Workshop',
    seats: 80,
    booked: 34,
    img: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=800&q=80&fit=crop',
    status: 'Open',
    description: 'Hands-on workshop for aspiring student entrepreneurs. Learn to develop your startup idea, build a team, and pitch to investors.',
    organizer: 'Faculty of Business',
  },
  {
    id: 4,
    title: 'Fine Arts Exhibition 2026',
    date: 'Jul 9, 2026',
    location: 'Arts Faculty Gallery, Floor 2',
    category: 'Cultural',
    seats: 150,
    booked: 90,
    img: 'https://images.unsplash.com/photo-1541367777708-7905fe3296c0?w=800&q=80&fit=crop',
    status: 'Open',
    description: 'Year-end showcase of student artworks including painting, sculpture, photography, and digital art. Open to all IAU students and staff.',
    organizer: 'Faculty of Fine Arts',
  },
  {
    id: 5,
    title: 'Inter-Faculty Sports Day',
    date: 'Aug 1, 2026',
    location: 'IAU Sports Complex',
    category: 'Sports',
    seats: 300,
    booked: 210,
    img: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80&fit=crop',
    status: 'Open',
    description: 'Annual inter-faculty sports competition featuring football, basketball, volleyball, and athletics. Represent your faculty and compete for the championship trophy.',
    organizer: 'Physical Education Department',
  },
  {
    id: 6,
    title: 'AI & Data Science Seminar',
    date: 'Aug 15, 2026',
    location: 'Rectorate Auditorium',
    category: 'Science',
    seats: 250,
    booked: 180,
    img: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80&fit=crop',
    status: 'Open',
    description: 'Industry experts share the latest advancements in artificial intelligence, machine learning, and data science. Ideal for all technical disciplines.',
    organizer: 'Computer Engineering Dept.',
  },
]

export const getEvents    = () => Promise.resolve(EVENTS)
export const getEventById = (id) => Promise.resolve(EVENTS.find(e => e.id === id))
